name: maize_watch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.19.0

  shared_preferences: ^2.5.3
  http: ^1.3.0
  
  icons_flutter: ^0.0.5
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  curved_navigation_bar: ^1.0.6
  syncfusion_flutter_charts: ^28.1.35
  flutter_local_notifications: ^19.1.0 
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  sqflite: ^2.4.2
  flutter_dotenv: ^5.2.1
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/l10n/
    - assets/images/
    - assets/fonts/
    - assets/gif/
    - assets/lottie/